CREATE TABLE IF NOT EXISTS queue_production_line (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EFFICIENCY_PERCENT INT NOT NULL,
    MATERIAL_WIDTH INT NOT NULL,
    MATERIAL VARCHAR(255) NOT NULL,
    MAIN_ELEMENT_ID INT NOT NULL,
    COMBINED_ELEMENT_ID INT,
    COUNT_ORDER_MAIN INT NOT NULL,
    COUNT_ORDER_COMBINED INT,
    QUANTITY_WIDTH_MAIN INT NOT NULL,
    QUANTITY_WIDTH_COMBINED INT,
    REMAINING_MAIN_QUANTITY INT NOT NULL,
    REMAINING_COMBINED_QUANTITY INT,
    USED_MAIN_QUANTITY INT NOT NULL,
    USED_COMBINED_QUANTITY INT,
    PLAN_MAIN_QUANTITY INT NOT NULL,
    PLAN_COMBINED_QUANTITY INT    
) ENGINE=InnoDB
